// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

// Документо-ориентированная или реляционная БД, например MongoDB или Postgres

Table feeds {
  id integer [primary key]
  user_id integer
  items json [note: 'Array of items']
  created_at timestamp
}

Table posts {
  id integer [primary key]
  text text(1000) [note: 'Content of the post']
  user_id integer
  latitude double
  longitude double
  created_at timestamp
}
